"""add 2 bool columns

Revision ID: 58ccf48d52d9
Revises: 825e6a2ea5f7
Create Date: 2025-12-15 09:19:39.050294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58ccf48d52d9'
down_revision: Union[str, None] = '825e6a2ea5f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('show_detailed_description', sa.Boolean(), nullable=True))
    op.add_column('projects', sa.Column('show_additional_information', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'show_additional_information')
    op.drop_column('projects', 'show_detailed_description')
    # ### end Alembic commands ###
