"""delete column comments

Revision ID: 8933efe5708d
Revises: 36a1be9a8e33
Create Date: 2025-07-13 12:02:26.854853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8933efe5708d'
down_revision: Union[str, None] = '36a1be9a8e33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Restaurants', 'comments')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Restaurants', sa.Column('comments', sa.VARCHAR(length=2500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
