"""add users id to table project

Revision ID: 9b83749d529f
Revises: d0eaab55be59
Create Date: 2025-11-07 15:00:02.875411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b83749d529f'
down_revision: Union[str, None] = 'd0eaab55be59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'projects', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'user_id')
    # ### end Alembic commands ###
