"""add column Additional_information

Revision ID: 825e6a2ea5f7
Revises: d895ade11cab
Create Date: 2025-12-02 14:58:03.051985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '825e6a2ea5f7'
down_revision: Union[str, None] = 'd895ade11cab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('Additional_information', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'Additional_information')
    # ### end Alembic commands ###
