"""add column is_favourite

Revision ID: 91c1ec888cc3
Revises: 8933efe5708d
Create Date: 2025-07-15 11:51:53.611781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91c1ec888cc3'
down_revision: Union[str, None] = '8933efe5708d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Restaurants', sa.Column('is_favourite', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Restaurants', 'is_favourite')
    # ### end Alembic commands ###
