"""nullable True for table users models

Revision ID: 50a58dbdd234
Revises: ee50c08d503d
Create Date: 2025-10-23 13:08:50.479891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50a58dbdd234'
down_revision: Union[str, None] = 'ee50c08d503d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'profile_description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('users', 'user_avatar',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'user_avatar',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'profile_description',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
